### ISSUE TITLE
Makefile does not consider updated .h files

### ISSUE THREAD

**Issue by PieBru** [piersfinlayson/otb-iot#4]
This probably is the root cause of issue #1 odd behaviour.

A quick solution may be force a `clean` directly in the Makefile:
`bin/app_image.elf: clean libmain2 otb_objects …`

Considered the complete build adds only few seconds to the update process, it may be preferable not to maintain a manually updated .h list in the Makefile.
Piero

**Comment by piersfinlayson** [comment]
Have updated the Makefile - which should take care of it:

Commit: https://github.com/piersfinlayson/otb-iot/commit/76d246658a0359f8b5ed2539e01131cacacfef95

**Comment by PieBru** [comment]
It works.
