### ISSUE TITLE
MQTT protocol level conflict

### ISSUE THREAD

**Issue by PieBru** [piersfinlayson/otb-iot#6]
`PROTOCOL_NAMEv31` and `PROTOCOL_NAMEv311` conflicts between mqtt_user_config.h and mqtt_defines.h
`PROTOCOL_NAMEv311` seems ignored because `PROTOCOL_NAMEv31` is the first checked in mqtt_msg.c.
Thanks,
Piero

**Comment by piersfinlayson** [comment]
Agree.  Removed.  https://github.com/piersfinlayson/otb-iot/commit/1447b3a4936d620c8325df0dde0e5acb73e40fa9
